### ISSUE TITLE
Files on the SIAL / D-tear update site overwrite ImageJ core files

### ISSUE THREAD

**Issue by haesleinhuepf** [d-tear/SIAL#1]
Dear David @d-tear ,

first of all congrats to the great JOSS submission! I'm happy to see that developers take care of issues lab-workers face on a daily basis. My personal highlight is the randomization tool. So good to have something like this available for the community!
I will in the coming days put some issues here on the github repository where we can discuss about details. Let's start :-)

While installing your plugin, I noticed that the update site contains some libraries which are also part of ImageJs core distribution. Your update site overwrites them. In other words: When installing your plugin in my Fiji, my Fiji gets downgraded (to February 2020). Please go through the list of jar files in the list and check if you programmed them and only upload your jar files and dependencies which are not available in core ImageJ. At least the blue marked files in this screenshot should be "marked obsolete" on the update site:
![image](https://user-images.githubusercontent.com/12660498/94715850-50a11b00-034e-11eb-991f-6f520ccb7831.png)

Furthermore (related), please update your pom-scijava from time to time [here](https://github.com/d-tear/SIAL/blob/master/pom.xml#L11) (current version is 29.2.1), recompile your plugin and update it on the update site. In that way you make sure that your code is compatible with the up-to-date Fiji distribution on your collaborators computers.

To test if everything works fine, I recommend having two Fiji installations: One where you put the jar files in and upload them to the update site, and another Fiji, where you just download the files from your update site to check if it works.

In case of any difficulties (I remember how I struggled when learning all this), just let me know. Either here in this thread or on [image.sc](https://image.sc) - there are also other plugin developers who are happy to help.

Best,
Robert

**Comment by haesleinhuepf** [comment]
Just linking: https://github.com/openjournals/joss-reviews/issues/2689

**Comment by d-tear** [comment]
Dear Robert @haesleinhuepf,

Thank you so much for your kind words and extremely helpful recommendations! Yep these issues definitely need to be corrected. I just started a new job this week so my schedule is a little hectic, but I will certainly find some time soon to correct these issues. In case of any difficulties, I'll also be sure to reach out for help either here or on image.sc. Learning to integrate everything with FIJI has been rewarding but also challenging :) I'll update this thread again when I've fixed these issues.

**Comment by haesleinhuepf** [comment]
Congrats to the new job! 🥳 Take your time and no hurry. Great things may take a while 🙂

**Comment by d-tear** [comment]
Hi Robert @haesleinhuepf ,

I've removed the core ImageJ files from the update site.  I also updated my pom file to 29.2.1 and recompiled my files and uploaded new copies to the update site.
Here's the files currently on the update site:

![Screen Shot 2020-10-04 at 11 36 58 AM](https://user-images.githubusercontent.com/19397687/95024163-3f019100-0636-11eb-946c-f57ed3d88fc0.png)


Please let me if you recommend any further changes. I really appreciate your help.

Best,

David

**Comment by haesleinhuepf** [comment]
Hey David @d-tear ,

alright, looks good! Thanks! I'll close this issue then :-)

I will continue reviewing in the coming days.

Best,
Robert
