### ISSUE TITLE
Fill out pom.xml file with correct details

### ISSUE THREAD

**Issue by haesleinhuepf** [d-tear/SIAL#2]
Hi again David @d-tear ,

I just discovered another rather minor issue: Please fill out the pom.xml file with correct details. These entries are important to know where issues can be reported, who programmed all this and what license applies to it. In daily practice, we Fiji-plugin developers copy all thoes entries from project to project. Thus, after doing this once right, it becomes easier. ;-)

In detail please specify:
* your organization [here](https://github.com/d-tear/SIAL/blob/master/pom.xml#L24-L25)
* if applicable your website [here](https://github.com/d-tear/SIAL/blob/master/pom.xml#L39)
* the correct license [here](https://github.com/d-tear/SIAL/blob/master/pom.xml#L71) and [here](https://github.com/d-tear/SIAL/blob/master/pom.xml#L29)
* the correct github-url [here](https://github.com/d-tear/SIAL/blob/master/pom.xml#L56-L63)

If there are any questions, let me know :-)

Best,
Robert

**Comment by haesleinhuepf** [comment]
Just linking: https://github.com/openjournals/joss-reviews/issues/2689

**Comment by d-tear** [comment]
Hi Robert @haesleinhuepf ,

Thank you for bringing this to my attention! Yes this needs to be corrected. I'll update this thread when I've corrected the pom (likely this wknd). Thanks for your help!

**Comment by d-tear** [comment]
Hi Robert @haesleinhuepf,

I've incorporated these edits into the pom file. Please let me know if you recommend any other changes or if I filled anything out incorrectly :)

Best,

David

**Comment by haesleinhuepf** [comment]
Hi David @d-tear ,

ok, perfect. If you like, you can improve the [indentation](https://github.com/d-tear/SIAL/blob/master/pom.xml#L83-L116) of the  file to improve readability. I personally see coding style as a matter of taste. Thus, I'll close this issue.

Best,
Robert
