### ISSUE TITLE
PhenoScoreKeeper: Default # phenotypes = 2?

### ISSUE THREAD

**Issue by bogovicj** [d-tear/SIAL#3]
Hi David @d-tear,

Congrats on the JOSS submission!

Does it make sense to have the default number of phenotypes equal to two?
(I don't see how anything less than two would be useful, but correct me if I'm wrong).

If so, I would also suggest constraining the min to be >= 2.

John

**Comment by bogovicj** [comment]
linking: https://github.com/openjournals/joss-reviews/issues/2689

**Comment by d-tear** [comment]
Hi John @bogovicj 

Thats a really good point! Yeah I can't imagine a scenario where somebody would be scoring less than 2 phenotypes.
So I agree that constraining the min to be >= 2 makes sense. I'll try to incorporate this constraint into the phenoscorekeeper plugin over the next couple of days. I'll update this thread when I've updated it.

Thanks!

**Comment by d-tear** [comment]
Hi @bogovicj ,

The minimum number of phenotypes is now >= 2
