### ISSUE TITLE
Community guidlines, links/references

### ISSUE THREAD

**Issue by haesleinhuepf** [d-tear/SIAL#4]
Hi @d-tear ,

I'm just going through the checklist of the JOSS and see two minor issues I would like to ask you to take care of:
* Please put a short statement in readme of your SIAL repository telling users (and potentially developers) how they can reach you in case they need support or want to contribute to the project.
* Please put some links and references in your documentation. For example, you are mentioning Cell Profiler, QuPath and Fiji. Why not link to their respective websites?

Thanks!

Best,
Robert

**Comment by haesleinhuepf** [comment]
https://github.com/openjournals/joss-reviews/issues/2689

**Comment by d-tear** [comment]
Hi @haesleinhuepf ,

These are great recommendations! In the repository readme I've added hyperlinks to FIJI, Cell Profiler, and QuPath (The paper contains references to the relevant publications). I also added a new section telling users/developers how they can contact me.
