### ISSUE TITLE
Anonymization versus Pseudonymization

### ISSUE THREAD

**Issue by haesleinhuepf** [d-tear/SIAL#5]
Hi @d-tear ,

I would like to ask you to think about clarifying some terminology in your software and in the documentation. In daily lab-life many people use the term "anonymization" but as later data analysis needs  association with the original names (e.g. patient names or file names), the correct term would be "pseudonymization" (see [wikipedia](https://en.wikipedia.org/wiki/Pseudonymization#:~:text=Pseudonymization%20is%20a%20data%20management,more%20artificial%20identifiers%2C%20or%20pseudonyms.)). Thus, I would ask you to at least clarify the difference in your documentation. I know people use these terms synonymously and that's why I think at least mentioning that there is a difference would be good to improve communication within the community.

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
https://github.com/openjournals/joss-reviews/issues/2689

**Comment by d-tear** [comment]
Hi @haesleinhuepf ,

Thanks for brining this to my attention. I've made efforts throughout the paper to use the more correct term of pseudonymization. In the repository readme, I also added a hyperlink to the wikipedia page for pseudonymization and added some additional sentences to differentiate pseudonymization vs anonymization
