### ISSUE TITLE
1.0.0 release, and avoid SNAPSHOT versions on update site

### ISSUE THREAD

**Issue by bogovicj** [d-tear/SIAL#6]
Hi @d-tear 

When you're ready, please release version 1.0.0 and add it to your update site. And in the future,
avoid putting SNAPSHOT versions on your update site.

This is because it makes it difficult to determine the state of the source code that corresponds to the distributed jar. From Fiji [Development lifecycle](https://imagej.net/Development_Lifecycle) :

> Using a SNAPSHOT version is saying "no guarantees are made as to the reproducibility of this artifact." For this reason, to best facilitate reproducible science, SNAPSHOT versions of code are not provided to users (except potentially for testing). 

Thanks!
John

**Comment by bogovicj** [comment]
https://github.com/openjournals/joss-reviews/issues/2689#issuecomment-715899953

**Comment by d-tear** [comment]
Hi @bogovicj ,

Thanks for brining this to my attention! It's a beginner mistake, my apologies. I removed the SNAPSHOT and have uploaded version 1.0.0 to my update site.

**Comment by bogovicj** [comment]
Nice! 

Can you please also tag the commit that corresponds to your 1.0.0 release?
You have one already for an older version (v0.1-Beta): https://github.com/d-tear/SIAL/tags

Thanks!

**Comment by d-tear** [comment]
Oh yeah that's def a good idea! I've tagged the commit that corresponds to the 1.0.0 release: https://github.com/d-tear/SIAL/tags
